[project]
authors = ["Tim-Oliver Buchholz <tim-oliver.buchholz@fmi.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "hdf5-to-zarr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
h5py = ">=3.11.0,<4"
jupyter = ">=1.1.1,<2"
bokeh = ">=3.5.2,<4"

[pypi-dependencies]
blosc2 = ">=2.7.1, <3"
faim-ipa = { path = "../../", editable = true }
